### ISSUE TITLE
CUBLAS_STATUS_INVALID_VALUE error when using

### ISSUE THREAD

**Issue by jby1993** [Picsart-AI-Research/Text2Video-Zero#22]
Hi, thank you for releasing the code. I have successfully installed the code, but when I run the demo code, there is a CUDA error
![image](https://user-images.githubusercontent.com/14065422/228869520-070d4fb5-460b-45cf-9089-cde8d798731f.png)
How can I fix this? My GPU is RTX 3090.

**Comment by johndpope** [comment]
python3 -c 'import torch;import gradio;import torchvision;print(f"gradio {gradio.__version__},\ntorch {torch.__version__},\ntorchvision {torchvision.__version__},  \ncuda {torch.version.cuda}, \ncudnn {torch.backends.cudnn.version()}")'


nvidia-smi

**Comment by jby1993** [comment]
Thanks, I found it's caused by incompatible cudnn runtime version and fixed it.

**Comment by johndpope** [comment]
hey @jby1993 - can you share your steps you took to fix?
my install is "working" but I get unexpected values for cuda + cudnn - did you just reinstall cudnn - or was it a path / environment fix? did you get 118 value back?

my install is here - I definitely have 11.8 installed - but I get this eroneous return of 117 - 

https://gist.github.com/johndpope/512bfb17c62b64a0ea624f9923c02988
```

torch.cuda.get_device_properties(0).multi_processor_count:82
gradio 3.23.0,
torch 2.0.0+cu117,
torchvision 0.15.1+cu117,  
cuda 11.7, 
cudnn 8500

```

**Comment by jby1993** [comment]
My cudnn version is 8.3.3 before, i reinstall 8.5.0 and it worked
